services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: 'postgres'
    image: postgres:16.3-alpine
    networks:
      - network
    env_file:
      - .env
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:${POSTGRES_PORT}


  redis:
    container_name: 'redis'
    image: redis:7.2.5-alpine
    networks:
      - network
    ports:
      - ${KV_STORE_PORT}:${KV_STORE_PORT}
networks:
  network:
